// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase configuration
// SECURITY: Never hardcode credentials - always use environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate required environment variables
if (!SUPABASE_URL) {
  throw new Error('Missing VITE_SUPABASE_URL environment variable. Check your .env.local file.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_ANON_KEY environment variable. Check your .env.local file.');
}

// Log configuration for debugging (only in development or when debug is enabled)
if (import.meta.env.DEV || import.meta.env.VITE_ENABLE_DEBUG === 'true') {
  console.log('[Supabase Config] URL:', SUPABASE_URL);
  console.log('[Supabase Config] Using project ID:', SUPABASE_URL.split('.')[0].split('//')[1]);
  
  // Validate correct project ID
  if (!SUPABASE_URL.includes('lkqekrhbxtbowaswvvqs')) {
    console.error('[Supabase Config] WARNING: Unexpected Supabase project ID detected!');
    console.error('[Supabase Config] Expected: lkqekrhbxtbowaswvvqs');
    console.error('[Supabase Config] Got:', SUPABASE_URL);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
