// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coekzxeqsavjmexwjlax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZWt6eGVxc2F2am1leHdqbGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDE2NDcsImV4cCI6MjA2MjkxNzY0N30.LA02pi1UZ9zlQQZCd4auv1XtQFQEGGXqMxdM_G8uklo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);